/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'createdBy' : IDL.Principal,
  'skillsRequired' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'approved' : IDL.Bool,
});
export const AppUserRole = IDL.Variant({
  'admin' : IDL.Null,
  'student' : IDL.Null,
  'industryPartner' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : AppUserRole,
  'email' : IDL.Text,
  'registrationTimestamp' : Time,
  'principalId' : IDL.Principal,
});
export const ContactRequest = IDL.Record({
  'to' : IDL.Principal,
  'from' : IDL.Principal,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getApprovedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getPlatformMetrics' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'getTotalProjects' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getUserRole' : IDL.Func([], [IDL.Opt(AppUserRole)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerNewUser' : IDL.Func([IDL.Text, IDL.Text, AppUserRole], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProject' : IDL.Func([Project], [], []),
  'sendContactRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'createdBy' : IDL.Principal,
    'skillsRequired' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'approved' : IDL.Bool,
  });
  const AppUserRole = IDL.Variant({
    'admin' : IDL.Null,
    'student' : IDL.Null,
    'industryPartner' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : AppUserRole,
    'email' : IDL.Text,
    'registrationTimestamp' : Time,
    'principalId' : IDL.Principal,
  });
  const ContactRequest = IDL.Record({
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getApprovedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
    'getPlatformMetrics' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'getTotalProjects' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getUserRole' : IDL.Func([], [IDL.Opt(AppUserRole)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerNewUser' : IDL.Func([IDL.Text, IDL.Text, AppUserRole], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProject' : IDL.Func([Project], [], []),
    'sendContactRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };