/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'admin' : null } |
  { 'student' : null } |
  { 'industryPartner' : null };
export interface ContactRequest {
  'to' : Principal,
  'from' : Principal,
  'message' : string,
}
export interface Project {
  'title' : string,
  'createdBy' : Principal,
  'skillsRequired' : Array<string>,
  'description' : string,
  'approved' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : AppUserRole,
  'email' : string,
  'registrationTimestamp' : Time,
  'principalId' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getApprovedProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactRequests' : ActorMethod<[], Array<ContactRequest>>,
  'getPlatformMetrics' : ActorMethod<[], [bigint, bigint]>,
  'getTotalProjects' : ActorMethod<[], bigint>,
  'getTotalUsers' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProjects' : ActorMethod<[], Array<Project>>,
  'getUserRole' : ActorMethod<[], [] | [AppUserRole]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, string, AppUserRole], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProject' : ActorMethod<[Project], undefined>,
  'sendContactRequest' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];